"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a[Math.floor(Math.random()*a.length)],chance=n=>Math.random()<n,wait=ms=>new Promise(r=>setTimeout(r,ms));
const CLASSES={
 knight:{name:"守護騎士",icon:"⚔️",resource:"體力 SP",maxRes:70,hp:145,atk:13,def:6,crit:7,speed:7,gain:14,desc:"高防禦，擅長格擋與穩定輸出",skills:[{n:"重斬",i:"🗡️",c:24,d:1.85,cd:1,t:"強力斬擊"},{n:"鐵壁架勢",i:"🛡️",c:22,guard:.32,cd:2,t:"獲得最大生命32%的護盾"},{n:"騎士禱言",i:"✨",c:38,heal:.32,cd:3,t:"恢復32%最大生命"}]},
 rogue:{name:"暗影盜賊",icon:"🗡️",resource:"能量 EN",maxRes:100,hp:100,atk:15,def:2,crit:18,speed:15,gain:22,desc:"高暴擊與閃避，擅長毒傷",skills:[{n:"背刺",i:"🌑",c:34,d:1.7,crit:35,cd:1,t:"高暴擊的致命一擊"},{n:"淬毒飛刃",i:"☠️",c:28,d:.65,poison:7,cd:2,t:"造成傷害並附加中毒"},{n:"幻影連擊",i:"💨",c:55,d:.72,hits:3,evade:25,cd:3,t:"三連擊並提升本回合閃避"}]},
 mage:{name:"元素法師",icon:"🔮",resource:"魔力 MP",maxRes:120,hp:92,atk:17,def:1,crit:11,speed:9,gain:12,desc:"消耗魔力施放元素魔法與回復術",skills:[{n:"烈焰彈",i:"🔥",c:30,d:1.65,burn:6,cd:1,t:"高傷害並附加燃燒"},{n:"冰封術",i:"❄️",c:38,d:1.1,stun:true,cd:3,t:"造成傷害並讓敵人停止一次"},{n:"生命回復術",i:"💚",c:42,heal:.42,cd:3,t:"恢復42%最大生命"}]},
 ranger:{name:"荒野獵人",icon:"🏹",resource:"專注 FP",maxRes:90,hp:110,atk:15,def:3,crit:15,speed:13,gain:18,desc:"遠距離破甲、連射與野外治療",skills:[{n:"穿甲箭",i:"🎯",c:27,d:1.55,pierce:true,cd:1,t:"無視敵人防禦與護盾"},{n:"疾風連射",i:"🏹",c:44,d:.68,hits:3,cd:2,t:"連續射出三支箭"},{n:"野外急救",i:"🌿",c:34,heal:.3,cleanse:true,cd:3,t:"恢復30%生命並清除異常"}]},
 priest:{name:"聖光祭司",icon:"🕊️",resource:"聖力 MP",maxRes:115,hp:108,atk:12,def:4,crit:9,speed:8,gain:14,desc:"強力治療、護盾與神聖攻擊",skills:[{n:"聖光裁決",i:"☀️",c:27,d:1.5,cd:1,t:"以聖光攻擊敵人"},{n:"大回復術",i:"💖",c:40,heal:.48,cd:3,t:"恢復48%最大生命"},{n:"神聖屏障",i:"🔆",c:35,guard:.48,cd:3,t:"獲得最大生命48%的護盾"}]},
 berserker:{name:"狂戰士",icon:"🪓",resource:"怒氣 RG",maxRes:100,hp:132,atk:18,def:2,crit:13,speed:9,gain:19,desc:"受傷累積怒氣，以生命換取爆發",skills:[{n:"血怒斬",i:"🩸",c:28,d:2,self:.06,cd:1,t:"高傷害但消耗6%生命"},{n:"戰吼",i:"📣",c:32,buff:1.4,cd:3,t:"接下來兩次攻擊提高40%"},{n:"狂亂風暴",i:"🌪️",c:65,d:.88,hits:3,leech:.22,cd:4,t:"三連擊並吸取22%傷害"}]}
};
const MATERIALS={gel:{n:"史萊姆凝膠",i:"🟢"},fang:{n:"野狼尖牙",i:"🦷"},wing:{n:"蝙蝠翼膜",i:"🦇"},cloth:{n:"哥布林布料",i:"🧵"},bone:{n:"不死骨片",i:"🦴"},silk:{n:"毒蛛絲",i:"🕸️"},ore:{n:"魔像礦核",i:"🪨"},dust:{n:"元素粉塵",i:"✨"},scale:{n:"飛龍鱗片",i:"🐉"},stone:{n:"強化石",i:"💎"}};
const GEAR={
 ironSword:{n:"狼牙騎士劍",i:"⚔️",slot:"weapon",atk:9,classes:["knight","berserker"],r:"rare",d:"以野狼尖牙加固的長劍。",cost:{gold:90,fang:5,ore:2}},shadowDaggers:{n:"影翼雙匕首",i:"🗡️",slot:"weapon",atk:10,crit:5,classes:["rogue"],r:"rare",d:"輕巧且難以察覺。",cost:{gold:90,wing:5,silk:2}},emberStaff:{n:"元素導能杖",i:"🔮",slot:"weapon",atk:12,classes:["mage","priest"],r:"rare",d:"引導元素與聖力的法杖。",cost:{gold:100,dust:5,ore:2}},hunterBow:{n:"裂牙獵弓",i:"🏹",slot:"weapon",atk:11,crit:3,classes:["ranger"],r:"rare",d:"兼具速度與穿透力。",cost:{gold:95,fang:3,silk:4}},
 dragonBlade:{n:"飛龍斷界刃",i:"🐲",slot:"weapon",atk:25,crit:5,classes:["knight","rogue","berserker"],r:"legendary",d:"飛龍素材打造的傳說兵器。",cost:{gold:520,scale:8,ore:10,stone:3}},archStaff:{n:"大賢者權杖",i:"🪄",slot:"weapon",atk:27,crit:4,classes:["mage","priest"],r:"legendary",d:"高度濃縮元素力量。",cost:{gold:520,dust:14,scale:5,stone:3}},dragonBow:{n:"龍脈星弓",i:"🌠",slot:"weapon",atk:26,crit:7,classes:["ranger"],r:"legendary",d:"箭矢如流星般貫穿敵人。",cost:{gold:520,scale:7,silk:10,stone:3}},
 hideArmor:{n:"魔獸皮甲",i:"🥋",slot:"armor",hp:32,def:3,r:"rare",d:"靈活而可靠的輕甲。",cost:{gold:80,cloth:5,fang:3}},boneArmor:{n:"不死骨鎧",i:"🦴",slot:"armor",hp:48,def:5,r:"epic",d:"以不死骨片強化的堅甲。",cost:{gold:180,bone:8,ore:5}},spiderCloak:{n:"夜蛛披風",i:"🕷️",slot:"armor",hp:38,def:3,speed:3,r:"epic",d:"提升速度與迴避空間。",cost:{gold:170,silk:8,wing:5}},dragonArmor:{n:"龍鱗聖鎧",i:"🛡️",slot:"armor",hp:95,def:10,r:"legendary",d:"能抵擋深境衝擊的最高級盔甲。",cost:{gold:650,scale:10,ore:12,stone:4}}
};
const POTIONS={red:{n:"生命藥水",i:"🧪",heal:.35,d:"恢復35%最大生命。"},full:{n:"完全回復藥",i:"💖",heal:1,d:"完全恢復生命與職業資源。"}};
const MONSTERS=[
 {n:"凝膠史萊姆",i:"🟢",hp:.85,atk:.8,def:0,drop:"gel"},{n:"月影蝙蝠",i:"🦇",hp:.7,atk:1.05,def:0,drop:"wing"},{n:"森林野狼",i:"🐺",hp:.92,atk:1.05,def:1,drop:"fang"},{n:"哥布林戰士",i:"👺",hp:1,atk:1,def:2,drop:"cloth"},{n:"骷髏衛兵",i:"💀",hp:1.12,atk:.95,def:4,drop:"bone"},{n:"劇毒魔蛛",i:"🕷️",hp:.88,atk:1.12,def:2,drop:"silk",poison:3},{n:"岩石魔像",i:"🗿",hp:1.35,atk:.9,def:7,drop:"ore"},{n:"烈焰精靈",i:"🔥",hp:.95,atk:1.18,def:3,drop:"dust",burn:3},{n:"深境飛龍",i:"🐉",hp:1.35,atk:1.16,def:6,drop:"scale"}
];
const BOSSES=[{n:"巨木守護者",i:"🌳",hp:2.45,atk:1.08,def:6,drop:"ore"},{n:"骸骨君王",i:"👑💀",hp:2.35,atk:1.18,def:8,drop:"bone"},{n:"赤焰飛龍王",i:"👑🐉",hp:2.55,atk:1.22,def:10,drop:"scale"}];
const DIFF={easy:{hp:.82,atk:.75,reward:1.1},normal:{hp:1,atk:1,reward:1},hard:{hp:1.22,atk:1.28,reward:1.25}},ZONES=["翠葉森林","暮色洞窟","亡者荒原","熔岩裂谷","龍眠深境"],RARITY={rare:"稀有",epic:"史詩",legendary:"傳說"};
let difficulty="normal",busy=false,selected=null;
let S={started:false,classId:"knight",floor:0,kills:0,gold:0,level:1,xp:0,xpNext:100,hp:100,res:0,baseHp:100,baseAtk:10,baseDef:2,crit:5,speed:8,shield:0,buffs:{},debuffs:{},cooldowns:[0,0,0],materials:{},potions:{},gear:[],equipped:{weapon:null,armor:null},enemy:null,lastRest:0,logs:[],difficulty:"normal",uid:1};
function baseClass(){return CLASSES[S.classId]}function gearByUid(uid){return S.gear.find(g=>g.uid===uid)}
function stats(){const out={maxHp:S.baseHp,atk:S.baseAtk,def:S.baseDef,crit:S.crit,speed:S.speed};for(const uid of Object.values(S.equipped)){const inst=gearByUid(uid),g=inst&&GEAR[inst.id];if(!g)continue;const mult=1+inst.level*.12;out.atk+=Math.round((g.atk||0)*mult);out.maxHp+=Math.round((g.hp||0)*mult);out.def+=Math.round((g.def||0)*mult);out.crit+=g.crit||0;out.speed+=g.speed||0}return out}
function save(){if(S.started)localStorage.setItem("abyss-adventure-v1",JSON.stringify(S))}function load(){try{const v=JSON.parse(localStorage.getItem("abyss-adventure-v1"));if(!v||!CLASSES[v.classId])return false;S={...S,...v,buffs:v.buffs||{},debuffs:v.debuffs||{},materials:v.materials||{},potions:v.potions||{},gear:v.gear||[]};difficulty=S.difficulty;return true}catch{return false}}
function startGame(id){const c=CLASSES[id];S={started:true,classId:id,floor:0,kills:0,gold:45,level:1,xp:0,xpNext:100,hp:c.hp,res:c.maxRes,baseHp:c.hp,baseAtk:c.atk,baseDef:c.def,crit:c.crit,speed:c.speed,shield:0,buffs:{},debuffs:{},cooldowns:[0,0,0],materials:{gel:1},potions:{red:2},gear:[],equipped:{weapon:null,armor:null},enemy:null,lastRest:0,logs:[],difficulty,uid:1};closeModal("startModal");log(`你以「${c.name}」開始了冒險。`,true);showExplore();render();save()}
function continueGame(){if(load()){S.enemy=null;S.shield=0;closeModal("startModal");showExplore();log("已繼續上次冒險。",true);render()}}
function createEnemy(elite=false){S.floor++;const boss=S.floor%5===0,m=pick(boss?BOSSES:MONSTERS.slice(clamp(Math.floor((S.floor-1)/3),0,MONSTERS.length-4),clamp(Math.floor((S.floor-1)/3)+4,4,MONSTERS.length))),d=DIFF[S.difficulty],growth=1+.095*(S.floor-1)+.0045*(S.floor-1)**2,eliteM=elite?1.38:1;const maxHp=Math.round(43*growth*m.hp*d.hp*eliteM),atk=Math.max(3,Math.round(7*(1+.068*(S.floor-1)+.0023*(S.floor-1)**2)*m.atk*d.atk*(elite?1.16:1)));S.enemy={...m,maxHp,hp:maxHp,atk,shield:0,effects:{burn:0,poison:0,weak:0},boss,elite,intent:null};S.shield=0;S.buffs={};S.debuffs={};S.cooldowns=[0,0,0];rollIntent();showBattle();log(`${boss?"首領":"魔物"}「${m.n}」出現！`,true);render();save()}
function rollIntent(){if(!S.enemy)return;const e=S.enemy,r=Math.random();if(r<.56)e.intent={type:"attack",icon:"⚔️",mult:1};else if(r<.73)e.intent={type:"heavy",icon:"💥",mult:1.55};else if(r<.88)e.intent={type:"guard",icon:"🛡️",value:Math.round(e.maxHp*.13)};else e.intent={type:"break",icon:"🔨",mult:.8}}
function intentText(){const e=S.enemy,x=e?.intent;if(!x)return"";if(x.type==="guard")return`防禦：護盾 ${x.value}`;const n=Math.round(e.atk*x.mult);return x.type==="heavy"?`蓄力重擊：約 ${n}`:x.type==="break"?`破防攻擊：約 ${n}`:`普通攻擊：約 ${n}`}
async function useSkill(key){if(busy||!S.enemy)return;const c=baseClass(),skill=key==="basic"?null:c.skills[+key];if(skill&&(S.res<skill.c||S.cooldowns[+key]>0)){toast(S.cooldowns[+key]>0?`技能還需等待 ${S.cooldowns[+key]} 回合`:"職業資源不足");return}busy=true;let total=0;if(!skill){S.res=Math.min(c.maxRes,S.res+c.gain);total=await dealDamage({d:1});log(`普通攻擊造成 ${total} 傷害，恢復 ${c.gain} 點資源。`)}else{S.res-=skill.c;S.cooldowns[+key]=skill.cd+1;if(skill.d){for(let i=0;i<(skill.hits||1);i++){total+=await dealDamage(skill);await wait(80)}}if(skill.guard){const n=Math.round(stats().maxHp*skill.guard);S.shield+=n;floatText(`護盾 +${n}`,"block",30,53)}if(skill.heal){const n=Math.round(stats().maxHp*skill.heal),before=S.hp;S.hp=Math.min(stats().maxHp,S.hp+n);floatText(`+${S.hp-before}`,"heal",30,53)}if(skill.burn)S.enemy.effects.burn+=skill.burn;if(skill.poison)S.enemy.effects.poison+=skill.poison;if(skill.stun)S.enemy.stunned=true;if(skill.cleanse)S.debuffs={};if(skill.evade)S.buffs.evade=skill.evade;if(skill.buff)S.buffs.power={mult:skill.buff,hits:2};if(skill.self)S.hp=Math.max(1,S.hp-Math.round(stats().maxHp*skill.self));if(skill.leech&&total)S.hp=Math.min(stats().maxHp,S.hp+Math.round(total*skill.leech));log(`施放「${skill.n}」${total?`，造成 ${total} 傷害`:""}。`,true)}render();if(S.enemy.hp<=0){await victory();busy=false;return}await wait(280);await enemyTurn();busy=false;render();save()}
async function dealDamage(skill){const st=stats(),crit=chance((st.crit+(skill.crit||0))/100),power=S.buffs.power?.mult||1,weak=S.debuffs.weak?0.8:1;let raw=Math.round(st.atk*skill.d*power*weak*(crit?1.65:1)*(.93+Math.random()*.14));if(!skill.pierce){const blocked=Math.min(S.enemy.shield,raw);S.enemy.shield-=blocked;raw=Math.max(1,raw-blocked-S.enemy.def)}S.enemy.hp-=raw;if(S.buffs.power&&--S.buffs.power.hits<=0)delete S.buffs.power;floatText(`${crit?"暴擊 ":""}-${raw}`,"damage",62,43);animateEnemy("hit");return raw}
async function enemyTurn(){const e=S.enemy;if(!e)return;if(e.effects.poison){const n=e.effects.poison;e.hp-=n;e.effects.poison=Math.max(0,n-1);floatText(`中毒 -${n}`,"damage",64,38);if(e.hp<=0){await victory();return}}if(e.stunned){e.stunned=false;log(`${e.n} 被冰封，無法行動！`)}else if(e.intent.type==="guard"){e.shield+=e.intent.value;log(`${e.n} 獲得 ${e.intent.value} 護盾。`)}else{animateEnemy("attack");await wait(220);let raw=Math.max(1,Math.round(e.atk*e.intent.mult)-stats().def);if(e.intent.type==="break"){S.shield=Math.floor(S.shield*.35);S.debuffs.weak=2}const dodge=clamp((stats().speed*.55+(S.buffs.evade||0))/100,0,.45);if(chance(dodge)){floatText("閃避","block",30,52);log("你閃開了攻擊！")}else{const block=Math.min(S.shield,raw),damage=raw-block;S.shield-=block;S.hp-=damage;if(S.classId==="berserker")S.res=Math.min(baseClass().maxRes,S.res+Math.round(damage*.8));floatText(damage?`-${damage}`:"完全格擋","damage",30,52);log(`${e.n} 造成 ${damage} 傷害。`);if(e.poison)S.debuffs.poison=(S.debuffs.poison||0)+e.poison;if(e.burn)S.debuffs.burn=(S.debuffs.burn||0)+e.burn}}if(e.effects.burn){const n=e.effects.burn;e.hp-=n;e.effects.burn=Math.max(0,n-1);floatText(`燃燒 -${n}`,"damage",66,38)}for(const type of ["poison","burn"]){if(S.debuffs[type]){S.hp-=S.debuffs[type];S.debuffs[type]=Math.max(0,S.debuffs[type]-1)}}S.cooldowns=S.cooldowns.map(x=>Math.max(0,x-1));S.buffs.evade=0;if(S.debuffs.weak>0)S.debuffs.weak--;if(S.hp<=0){defeat();return}if(e.hp<=0){await victory();return}rollIntent()}
async function victory(){const e=S.enemy;if(!e)return;const d=DIFF[S.difficulty],gold=Math.round((14+S.floor*2.7)*(e.boss?2.7:e.elite?1.7:1)*d.reward),xp=Math.round((30+S.floor*3.5)*(e.boss?2.2:e.elite?1.55:1));S.gold+=gold;S.xp+=xp;S.kills++;const dropN=(e.boss?4:e.elite?2:1)+Math.floor(Math.random()*2);addMaterial(e.drop,dropN);if(e.elite||e.boss||chance(.16))addMaterial("stone",e.boss?3:1);if(chance(.16))S.potions.red=(S.potions.red||0)+1;log(`討伐成功：獲得 ${gold} 金幣、${xp} EXP、${MATERIALS[e.drop].n}×${dropN}。`,true);toast(`討伐成功 · +${xp} EXP`);S.enemy=null;S.shield=0;await wait(350);while(S.xp>=S.xpNext){S.xp-=S.xpNext;S.level++;S.xpNext=Math.round(100*Math.pow(S.level,1.3));S.baseHp+=11;S.baseAtk+=2;S.baseDef+=S.level%2;S.hp=stats().maxHp;S.res=baseClass().maxRes;toast(`升級！目前 Lv.${S.level}`);log(`升到 Lv.${S.level}，能力提升並完全恢復。`,true)}showExplore();render();save()}
function defeat(){S.enemy=null;S.gold=Math.floor(S.gold*.75);S.floor=Math.max(0,S.floor-2);S.hp=stats().maxHp;S.res=baseClass().maxRes;openEvent("☠️","冒險失敗","你被送回兩區前，損失25%金幣；素材與裝備保留。",[{label:"重新整備",run:()=>{closeModal("eventModal");showExplore();render();save()}}])}
function tryFlee(){if(!S.enemy||busy)return;busy=true;const rate=clamp(.45+(stats().speed-S.floor)*.015,.25,.8);if(chance(rate)){log("成功逃離戰鬥。",true);S.enemy=null;showExplore();busy=false;render();save()}else{toast("逃跑失敗");enemyTurn().then(()=>{busy=false;render();save()})}}
function chooseRoute(type){if(busy||S.enemy)return;if(type==="rest"){rest();return}if(type==="elite"){createEnemy(true);return}S.floor++;const next=S.floor;S.floor--;if(next%5===0){createEnemy(false);return}const r=Math.random();if(r<.72)createEnemy(false);else if(r<.88)treasure();else event()}
function rest(){if(S.floor-S.lastRest<3){toast(`再前進 ${3-(S.floor-S.lastRest)} 區才能休息`);return}S.lastRest=S.floor;S.hp=Math.min(stats().maxHp,S.hp+Math.round(stats().maxHp*.45));S.res=baseClass().maxRes;S.potions.red=(S.potions.red||0)+1;log("營地休息：恢復生命、職業資源並獲得生命藥水。",true);render();save()}
function treasure(){S.floor++;const gold=25+S.floor*3;S.gold+=gold;const mat=pick(Object.keys(MATERIALS).filter(x=>x!=="stone"));addMaterial(mat,2);openEvent("🎁","冒險寶箱",`找到 ${gold} 金幣與 ${MATERIALS[mat].n}×2。`,[{label:"收下",run:()=>{closeModal("eventModal");showExplore();render();save()}}])}
function event(){S.floor++;const heal=Math.round(stats().maxHp*.35);openEvent("⛲","古老泉水","泉水散發柔和光芒，你可以恢復生命或汲取能量。",[{label:"恢復生命",hint:`恢復 ${heal} HP`,run:()=>{S.hp=Math.min(stats().maxHp,S.hp+heal);finishEvent("傷口逐漸癒合。") }},{label:"汲取能量",hint:"職業資源全滿",run:()=>{S.res=baseClass().maxRes;finishEvent("力量重新充滿全身。")}}])}
function finishEvent(msg){closeModal("eventModal");log(msg,true);showExplore();render();save()}function addMaterial(id,n){S.materials[id]=(S.materials[id]||0)+n}
function buyGear(id){if(S.enemy){toast("戰鬥中無法製作裝備");return}const g=GEAR[id];if(g.classes&&!g.classes.includes(S.classId)){toast("目前職業無法使用這把武器");return}if(!canPay(g.cost)){toast("金幣或素材不足");return}pay(g.cost);S.gear.push({uid:S.uid++,id,level:0});log(`製作完成：「${g.n}」。`,true);toast(`獲得裝備：${g.n}`);render();save()}
function canPay(cost){return Object.entries(cost).every(([k,v])=>k==="gold"?S.gold>=v:(S.materials[k]||0)>=v)}function pay(cost){for(const [k,v] of Object.entries(cost))k==="gold"?S.gold-=v:S.materials[k]-=v}
function enhance(uid){if(S.enemy){toast("戰鬥中無法強化");return}const inst=gearByUid(uid);if(!inst||inst.level>=9)return;const next=inst.level+1,cost={gold:30*next*next,stone:Math.max(1,Math.ceil(next/2))};if(!canPay(cost)){toast("強化石或金幣不足");return}pay(cost);const rates=[1,1,.95,.9,.82,.72,.62,.52,.42][inst.level];if(chance(rates)){inst.level++;toast(`強化成功：＋${inst.level}`);log(`${GEAR[inst.id].n} 強化至＋${inst.level}。`,true)}else{toast("強化失敗，裝備沒有損壞");log(`${GEAR[inst.id].n} 強化失敗，等級維持。`)}render();save()}
function equip(uid){if(S.enemy){toast("戰鬥中無法更換裝備");return}const inst=gearByUid(uid),g=inst&&GEAR[inst.id];if(!g)return;if(g.classes&&!g.classes.includes(S.classId)){toast("目前職業不能裝備");return}S.equipped[g.slot]=S.equipped[g.slot]===uid?null:uid;S.hp=Math.min(S.hp,stats().maxHp);closeModal("itemModal");log(`${S.equipped[g.slot]?"裝備":"卸下"}「${g.n}${inst.level?`＋${inst.level}`:""}」。`);render();save()}
function usePotion(id){if(!(S.potions[id]>0))return;const p=POTIONS[id],before=S.hp;S.potions[id]--;S.hp=Math.min(stats().maxHp,S.hp+Math.round(stats().maxHp*p.heal));if(id==="full")S.res=baseClass().maxRes;closeModal("itemModal");floatText(`+${S.hp-before}`,"heal",30,53);render();save()}
function showExplore(){$("#sceneCopy").classList.remove("hidden");$("#sceneCopy").innerHTML=`<p class="eyebrow">第 ${S.floor+1} 區</p><h2>${S.floor%5===4?"強大的首領氣息就在前方":"冒險道路延伸至迷霧深處"}</h2><p>整理裝備與素材，準備好後繼續探索。</p>`;$("#enemyWrap").classList.remove("active");$("#enemyCard").classList.add("hidden");$("#enemyIntent").classList.add("hidden");$("#skillBar").classList.add("hidden");$("#exploreActions").classList.remove("hidden");$("#fleeBtn").classList.add("hidden");$("#turnKicker").textContent="探索階段";$("#turnText").textContent="選擇下一步"}
function showBattle(){$("#sceneCopy").classList.add("hidden");$("#enemyWrap").classList.add("active");$("#enemyCard").classList.remove("hidden");$("#enemyIntent").classList.remove("hidden");$("#skillBar").classList.remove("hidden");$("#exploreActions").classList.add("hidden");$("#fleeBtn").classList.remove("hidden");$("#turnKicker").textContent="戰鬥中";$("#turnText").textContent="選擇攻擊或職業技能"}
function render(){const c=baseClass(),st=stats();S.hp=clamp(S.hp,0,st.maxHp);S.res=clamp(S.res,0,c.maxRes);$("#floorText").textContent=S.floor;$("#goldText").textContent=S.gold;$("#killText").textContent=S.kills;$("#levelText").textContent=S.level;$("#classText").textContent=c.name;$("#playerPortrait").textContent=c.icon;setMeter("hp",S.hp,st.maxHp);$("#resourceName").textContent=c.resource;$("#resourceLabel").textContent=`${Math.ceil(S.res)} / ${c.maxRes}`;$("#resourceBar").style.width=`${S.res/c.maxRes*100}%`;setMeter("xp",S.xp,S.xpNext);$("#xpAway").textContent=`距離升級還差 ${S.xpNext-S.xp} EXP`;$("#atkText").textContent=st.atk;$("#defText").textContent=st.def;$("#critText").textContent=`${st.crit}%`;$("#speedText").textContent=st.speed;$("#zoneText").textContent=ZONES[Math.min(ZONES.length-1,Math.floor(S.floor/5))];$("#arena").classList.toggle("low-hp",S.hp/st.maxHp<.28);renderEquipment();renderSkills();renderEnemy();renderBag();renderShop();renderUpgrade();renderEffects();$("[data-route=rest]").disabled=S.floor-S.lastRest<3}
function setMeter(id,v,m){$(`#${id}Label`).textContent=`${Math.ceil(v)} / ${m}`;$(`#${id}Bar`).style.width=`${clamp(v/m*100,0,100)}%`}
function renderSkills(){const c=baseClass();$("#classSkills").innerHTML=c.skills.map((s,i)=>`<button class="skill-command" data-skill="${i}" ${!S.enemy||busy||S.res<s.c||S.cooldowns[i]>0?"disabled":""}><span>${s.i}</span><div><small>${S.cooldowns[i]?`冷卻 ${S.cooldowns[i]} 回合`:`消耗 ${s.c}`}</small><b>${s.n}</b><p>${s.t}</p></div></button>`).join("");const basic=$("[data-skill=basic]");if(basic)basic.disabled=!S.enemy||busy}
function renderEnemy(){const e=S.enemy;if(!e)return;$("#enemySprite").textContent=e.i;$("#enemyName").textContent=e.n;$("#enemyRank").textContent=e.boss?"深境首領":e.elite?"菁英魔物":"普通魔物";$("#enemyLevel").textContent=`Lv.${S.floor}`;$("#enemyHpLabel").textContent=`${Math.max(0,e.hp)} / ${e.maxHp}${e.shield?`　🛡️${e.shield}`:""}`;$("#enemyHpBar").style.width=`${clamp(e.hp/e.maxHp*100,0,100)}%`;$("#intentIcon").textContent=e.intent.icon;$("#intentText").textContent=intentText();$("#enemyEffects").textContent=`${e.effects.burn?`🔥${e.effects.burn} `:""}${e.effects.poison?`☠️${e.effects.poison}`:""}`}
function renderEquipment(){for(const slot of ["weapon","armor"]){const inst=gearByUid(S.equipped[slot]),g=inst&&GEAR[inst.id];$(`#${slot}Icon`).textContent=g?.i||(slot==="weapon"?baseClass().icon:"🧥");$(`#${slot}Name`).textContent=g?`${g.n}${inst.level?`＋${inst.level}`:""}`:(slot==="weapon"?"新手武器":"旅人布衣")}}
function renderEffects(){const a=[];if(S.shield)a.push(`🛡️ 護盾 ${S.shield}`);if(S.buffs.power)a.push(`📣 強攻 ${S.buffs.power.hits}`);if(S.debuffs.poison)a.push(`☠️ 中毒 ${S.debuffs.poison}`);if(S.debuffs.burn)a.push(`🔥 燃燒 ${S.debuffs.burn}`);$("#playerEffects").innerHTML=a.map(x=>`<span class="effect-chip">${x}</span>`).join("")}
function bagEntries(){const f=$(".filter.active")?.dataset.filter||"all",arr=[];for(const [id,n] of Object.entries(S.potions))if(n&&["all","potion"].includes(f))arr.push({kind:"potion",id,n,name:POTIONS[id].n,icon:POTIONS[id].i,sub:"藥品"});for(const [id,n] of Object.entries(S.materials))if(n&&["all","material"].includes(f))arr.push({kind:"material",id,n,name:MATERIALS[id].n,icon:MATERIALS[id].i,sub:"素材"});if(["all","equipment"].includes(f))for(const g of S.gear){const x=GEAR[g.id];arr.push({kind:"gear",id:g.uid,n:1,name:`${x.n}${g.level?`＋${g.level}`:""}`,icon:x.i,sub:`${x.slot==="weapon"?"武器":"盔甲"} · ${RARITY[x.r]}`})}return arr}
function renderBag(){const a=bagEntries();$("#bagCount").textContent=Object.values(S.potions).reduce((a,b)=>a+b,0)+Object.values(S.materials).reduce((a,b)=>a+b,0)+S.gear.length;$("#inventoryList").innerHTML=a.length?a.map(x=>`<button class="item-row" data-kind="${x.kind}" data-id="${x.id}"><span class="item-icon">${x.icon}</span><span class="item-copy"><b>${x.name}</b><small>${x.sub}</small></span><span class="item-count">×${x.n}</span></button>`).join(""):`<div class="inventory-empty">目前沒有這類物品</div>`}
function costText(cost){return Object.entries(cost).map(([k,v])=>k==="gold"?`🪙${v}`:`${MATERIALS[k].i}${v}`).join("　")}
function renderShop(){$("#shopList").innerHTML=Object.entries(GEAR).filter(([,g])=>!g.classes||g.classes.includes(S.classId)).map(([id,g])=>`<div class="shop-row"><span>${g.i}</span><div class="shop-copy"><b>${g.n}</b><small>${g.d}<br>${costText(g.cost)}</small></div><button data-buy="${id}" ${!canPay(g.cost)||S.enemy?"disabled":""}>製作</button></div>`).join("")}
function renderUpgrade(){const list=S.gear;$("#upgradeList").innerHTML=list.length?list.map(x=>{const g=GEAR[x.id],next=x.level+1,cost={gold:30*next*next,stone:Math.max(1,Math.ceil(next/2))},rate=x.level>=9?0:[100,100,95,90,82,72,62,52,42][x.level];return`<div class="upgrade-row"><span>${g.i}</span><div class="shop-copy"><b>${g.n} <span class="enhance-level">＋${x.level}</span></b><small>${x.level>=9?"已達最高強化":"成功率 "+rate+"% · "+costText(cost)}</small></div><button data-enhance="${x.uid}" ${x.level>=9||!canPay(cost)||S.enemy?"disabled":""}>強化</button></div>`}).join(""):`<div class="inventory-empty">先在商店製作一件裝備</div>`}
function openItem(kind,id){selected={kind,id};let name,icon,desc,statsHtml="",primary=null;if(kind==="potion"){const p=POTIONS[id];name=p.n;icon=p.i;desc=p.d;primary={label:"使用",run:()=>usePotion(id),disabled:S.hp>=stats().maxHp&&id!=="full"}}else if(kind==="material"){const m=MATERIALS[id];name=m.n;icon=m.i;desc="怪物掉落的製作與強化素材。";statsHtml=`<div>持有<br><b>${S.materials[id]||0}</b></div>`}else{const inst=gearByUid(+id),g=inst&&GEAR[inst.id];if(!g)return;name=`${g.n}${inst.level?`＋${inst.level}`:""}`;icon=g.i;desc=g.d;const mult=1+inst.level*.12;statsHtml=[["攻擊",g.atk&&Math.round(g.atk*mult)],["生命",g.hp&&Math.round(g.hp*mult)],["防禦",g.def&&Math.round(g.def*mult)],["暴擊",g.crit&&g.crit+"%"],["速度",g.speed]].filter(x=>x[1]).map(x=>`<div>${x[0]}<br><b>＋${x[1]}</b></div>`).join("");primary={label:S.equipped[g.slot]===inst.uid?"卸下":"裝備",run:()=>equip(inst.uid)}}$("#itemIcon").textContent=icon;$("#itemTitle").textContent=name;$("#itemRarity").textContent=kind==="gear"?RARITY[GEAR[gearByUid(+id).id].r]:kind==="material"?"素材":"消耗品";$("#itemDescription").textContent=desc;$("#itemStats").innerHTML=statsHtml;const box=$("#itemActions");box.innerHTML="";box.append(button("關閉",()=>closeModal("itemModal")));if(primary){const b=button(primary.label,primary.run,"primary");b.disabled=primary.disabled||false;box.append(b)}openModal("itemModal")}
function log(msg,important=false){S.logs.unshift({msg,important,t:new Date().toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})});S.logs=S.logs.slice(0,60);$("#logPage").innerHTML=S.logs.map(x=>`<div class="log-row ${x.important?"important":""}"><small>${x.t}</small>　${x.msg}</div>`).join("")}
function floatText(t,c,x,y){const n=document.createElement("span");n.className=`float-text ${c}`;n.textContent=t;n.style.left=x+"%";n.style.top=y+"%";$("#floatLayer").append(n);setTimeout(()=>n.remove(),1050)}function animateEnemy(c){const e=$("#enemyWrap");e.classList.remove(c);void e.offsetWidth;e.classList.add(c);setTimeout(()=>e.classList.remove(c),380)}function toast(t){const n=document.createElement("div");n.className="toast";n.textContent=t;$("#toastStack").append(n);setTimeout(()=>n.remove(),2600)}function button(t,run,c=""){const b=document.createElement("button");b.textContent=t;b.className=c;b.onclick=run;return b}function openModal(id){$("#"+id).classList.add("open")}function closeModal(id){$("#"+id).classList.remove("open")}function openEvent(i,t,d,opts){$("#eventIcon").textContent=i;$("#eventTitle").textContent=t;$("#eventDescription").textContent=d;const b=$("#eventOptions");b.innerHTML="";for(const o of opts){const x=button(o.label,o.run,o.primary?"primary":"");if(o.hint)x.innerHTML=`${o.label}<small>${o.hint}</small>`;b.append(x)}openModal("eventModal")}
document.addEventListener("click",e=>{const sk=e.target.closest("[data-skill]");if(sk)useSkill(sk.dataset.skill);const r=e.target.closest("[data-route]");if(r)chooseRoute(r.dataset.route);const it=e.target.closest("[data-kind]");if(it)openItem(it.dataset.kind,it.dataset.id);const buy=e.target.closest("[data-buy]");if(buy)buyGear(buy.dataset.buy);const up=e.target.closest("[data-enhance]");if(up)enhance(+up.dataset.enhance);const sl=e.target.closest("[data-equip-slot]");if(sl&&S.equipped[sl.dataset.equipSlot])openItem("gear",S.equipped[sl.dataset.equipSlot]);const c=e.target.closest("[data-close]");if(c)closeModal(c.dataset.close);const tab=e.target.closest("[data-tab]");if(tab){$$('[data-tab]').forEach(x=>x.classList.toggle("active",x===tab));$$('.tab-page').forEach(x=>x.classList.remove("active"));$("#"+tab.dataset.tab+"Page").classList.add("active")}const f=e.target.closest("[data-filter]");if(f){$$('[data-filter]').forEach(x=>x.classList.toggle("active",x===f));renderBag()}});
$("#classGrid").innerHTML=Object.entries(CLASSES).map(([id,c])=>`<button class="class-card" data-class="${id}"><span>${c.icon}</span><b>${c.name}</b><small>${c.desc}</small><em>${c.resource} · ${c.maxRes}</em></button>`).join("");$("#classGrid").onclick=e=>{const b=e.target.closest("[data-class]");if(b)startGame(b.dataset.class)};$("#difficultyButtons").onclick=e=>{const b=e.target.closest("[data-difficulty]");if(b){difficulty=b.dataset.difficulty;$$('[data-difficulty]').forEach(x=>x.classList.toggle("active",x===b))}};$("#continueBtn").onclick=continueGame;$("#fleeBtn").onclick=tryFlee;$("#helpBtn").onclick=()=>openModal("helpModal");$("#resetBtn").onclick=()=>{if(confirm("確定刪除存檔並重新選擇職業嗎？")){localStorage.removeItem("abyss-adventure-v1");location.reload()}};if(localStorage.getItem("abyss-adventure-v1"))$("#continueBtn").classList.remove("hidden");render();
